# Description:
## Import Python libraries and user-defined modules

In [9]:
%pip install nltk openpyxl

Collecting nltk
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting click (from nltk)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in C:\WPy64-313130\notebooks\Envs\bda_env\Lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.5.9-cp313-cp313-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in C:\WPy64-313130\notebooks\Envs\bda_env\Lib\site-packages (from nltk) (4.68.2)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: colorama in C:\WPy64-313130\notebooks\Envs\bda_env\Lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 254.9 kB/s eta 0:00:05
   ------------- -------------------------- 0.5/1.6 MB 254.9 kB/s eta 0:00:05
   ------------- -------------------------- 0.5/1.6 MB 254.9 kB/s eta 0:00:05
   ------------- -------------------------- 0.5/1.6 MB 254.9 kB/s eta 0:00:05
   ------------- -------------------------- 0.5/1.6 MB 254.9 kB/s eta 0:00:05
   ------------- -------------------------- 0.5/1.6 MB 254.9 kB/s eta 0:00:05
   -------------------- ------------------- 0.8/1.6 MB 231.7 kB/s eta 0:00:04
   -------------------- ------------------- 0.8/1.6 MB 231.7 kB/s eta 0:00:04
   -------------------- ------------------- 0.8/1.6 MB 231.7 kB/s eta 0:00:04
   -------------------- ------------------- 0.8/1.6 MB 231.7 kB/s eta 0:00:04
   -------------------- ------------------- 0.8/1.6 MB 231.7 kB/s eta 0:00:04
   -------------------- ------------------- 0.8/1.6 MB 231.7 kB/s eta 0:00:04
   --------------------------- ------------ 1.0/1.6 MB 227.8 kB/s eta 0:00:03
   --------------------------- ------------ 1.0/1.6 MB 227.8 kB/s eta 0:00:03
   --------------------------- ------------ 1.0/1.6 MB 227.8 kB/s eta 0:00:03
   --------------------------- ------------ 1.0/1.6 MB 227.8 kB/s eta 0:00:03
   --------------------------- ------------ 1.0/1.6 MB 227.8 kB/s eta 0:00:03
   --------------------------------- ------ 1.3/1.6 MB 228.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.3/1.6 MB 228.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.3/1.6 MB 228.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.3/1.6 MB 228.9 kB/s eta 0:00:02
   --------------------------------- ------ 1.3/1.6 MB 228.9 kB/s eta 0:00:02
   ---------------------------------------- 1.6/1.6 MB 231.1 kB/s  0:00:07
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading regex-2026.5.9-cp313-cp313-win_amd64.whl (277 kB)
Downloading click-8.4.1-py3-none-any.whl (116 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: regex, et-xmlfile, click, openpyxl, nltk

   ---------------------------------------- 0/5 [regex]
   ---------------------------------------- 0/5 [regex]
   ---------------------------------------- 0/5 [regex]
   -------- ------------------------------- 1/5 [et-xmlfile]
   -------- ------------------------------- 1/5 [et-xmlfile]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   ------------------------ --------------- 3/5 [openpyxl]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   ---------------------------------------- 5/5 [nltk]

Successfully installed click-8.4.1 et-xmlfile-2.0.0 nltk-3.9.4 openpyxl-3.1.5 regex-2026.5.9
Note: you may need to restart the kernel to use updated packages.

In [10]:
import warnings
warnings.filterwarnings("ignore")
#from dotenv import load_dotenv
import os
import time
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import ydata_profiling
from ydata_profiling import ProfileReport

### import prep.preprocessing as prep

### import os
### os.getcwd()

In [11]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\moath\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\moath\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\moath\AppData\Roaming\nltk_data...

True

### Load variables from .env file

In [12]:
#load_dotenv()

XLSX_FILES_FOLDER = "../data/xlsx"
HTML_REPORTS_FOLDER = "../reports"

XLSX_FILES_FOLDER, HTML_REPORTS_FOLDER

('../data/xlsx', '../reports')

### Read the dataset and high-level EDA

In [16]:
#df = read_excel_files(XLSX_FILES_FOLDER, pattern, debug=True)
df= pd.read_excel(XLSX_FILES_FOLDER+"/image_metadata.xlsx", sheet_name="Sheet1")

In [17]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

## Add more stopwords
stop_words.add("two")

def preprocess(text):

    text = text.lower()

    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)

    tokens = text.split()#I love Palestine

    tokens = [
        lemmatizer.lemmatize(w)
        for w in tokens
        if w not in stop_words and len(w) > 2
    ]

    return " ".join(tokens)

In [18]:
#df.shape ##(502, 9)
## This from pandas syntax, please watch the pandas review.
df["caption_clean"] = df["caption"].apply(preprocess)

In [19]:
df.head()

,project_id,category,image_id,caption,caption_ai,caption_clean
0,212,Reflector,20180105_101214,a large stainless steel disc with a milled sur...,NaN,large stainless steel disc milled surface
1,212,Reflector,20180105_101224,a rectangular steel plate,NaN,rectangular steel plate
2,212,Reflector,20180302_135657,"Housing of the beryllium reflector, clamped wi...",NaN,housing beryllium reflector clamped six black ...
3,212,Reflector,20180302_135706,"Housing of the beryllium reflector, clamped wi...",NaN,housing beryllium reflector clamped six black ...
4,212,Reflector,20180418-Vortest-1,Mounted housing of the beryllium reflector on ...,NaN,mounted housing beryllium reflector traversing...

In [20]:
col_to_drop = "caption_ai"
df_ic = None

if col_to_drop in df.columns:
    df_ic = df.drop(columns=[col_to_drop])
df_ic.head()

,project_id,category,image_id,caption,caption_clean
0,212,Reflector,20180105_101214,a large stainless steel disc with a milled sur...,large stainless steel disc milled surface
1,212,Reflector,20180105_101224,a rectangular steel plate,rectangular steel plate
2,212,Reflector,20180302_135657,"Housing of the beryllium reflector, clamped wi...",housing beryllium reflector clamped six black ...
3,212,Reflector,20180302_135706,"Housing of the beryllium reflector, clamped wi...",housing beryllium reflector clamped six black ...
4,212,Reflector,20180418-Vortest-1,Mounted housing of the beryllium reflector on ...,mounted housing beryllium reflector traversing...

In [21]:
#df_ic.info()

### Generate Reports using YData/YData-SDK Profiling

In [22]:
import time

In [23]:
start = time.time()
title = "IC for Archive Projects-ITE"

#profile = ProfileReport(df_ic, title=f"{title}", minimal=False, correlations={"pearson": {"calculate": True}, "spearman": {"calculate": True}})
profile = ProfileReport(df_ic, title=f"{title}")

out_html = HTML_REPORTS_FOLDER + f"/{title}.html"
profile.to_file(out_html)

end = time.time()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/5 [00:00<?, ?it/s]
100%|██████████| 5/5 [00:00<00:00, 12.88it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [24]:
minutes = (end - start) / 60
print(f"Report generated in {minutes:.2f} minutes")

Report generated in 0.29 minutes